spring.application.name=journalApp
spring.data.mongodb.host=localhost
spring.data.monngdb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongdb.username=myjournaluser
#srping.data.mongodb.password=mypassword